// This file defines the structure of the data models for documentation purposes.
// It is used to generate a JSON representation of the system's data structure.

export const incidentStructure = {
  id: "string (autogenerated, e.g., 'INC-001')",
  title: "string",
  description: "string",
  status: "'Identificación' | 'Contención' | 'Mitigación' | 'Recuperación' | 'Post-incidente' | 'Cerrado'",
  severity: "'Low' | 'Medium' | 'High' | 'Critical'",
  reportedAt: "string (ISO 8601 Date)",
  reporter: {
    name: "string",
    email: "string (email format)",
  },
  assignedTo: {
    name: "string",
    email: "string (email format)",
  },
  updates: "Array of { timestamp: string (ISO 8601 Date), update: string }",
  workstreamAssignment: {
    scoping: "string (assignee name)",
    triage: "string (assignee name)",
    intelligence: "string (assignee name)",
    impact: "string (assignee name)",
  },
  workstreamTracker: "Array of { id: string, date: string, priority: 'Alta'|'Media'|'Baja', status: 'New'|'In Progress'|'Complete'|'In Review'|'Backlog', workstream: string, task: string, assignedTo: string, dateUpdate: string, dateComplete: string }",
  systems: "Array of { id: string, status: string, earliestEvidence: string, latestEvidence: string, hostname: string, ipAddress: string, domain: string, systemRole: string, systemOperating: string, details: string, notes: string }",
  hostIndicators: "Array of { id: string, fullPath: string, sha256: string, sha1: string, md5: string, earliestEvidence: string, latestEvidence: string, attackAlignment: string, notes: string }",
  networkIndicators: "Array of { id: string, assignment: string, status: 'Sospechoso'|'Confirmado'|'Under Investigation'|'Unrelated', indicator: string, detail: string, latestEvidence: string, source: string, notes: string }",
  intelligence: {
    status: "'Red' | 'Yellow' | 'Green'",
    rfi: "'Unanswered' | 'Awaiting Response' | 'Answered'",
    response: "string",
    sourceFile: "string (filename)",
  },
  evidenceTracker: "Array of { id: string, evidenceType: string, evidenceSource: string, date: string, dateReceived: string, evidenceLocation: string, notes: string }",
  applications: "Array of { id: string, submittedBy: string, status: 'compromised-malware' | 'tools' | 'config-changes' | 'accessed-confirmed' | 'unauthorized-access' | 'potentially-accessed' | 'suspected-unauthorized-access' }",
  forensics: "Array of { id: string, highFidelityForensicKeywords: string, note: string }",
  authorization: {
    authorizerName: "string",
    authorizerRank: "string",
    catalog: "string",
  },
};

export const detectionStructure = {
    id: "string (autogenerated, e.g., 'DET-001')",
    tipo_incidente: "string",
    prioridad: "'Baja' | 'Media' | 'Alta' | 'Crítica'",
    fecha_incidente: "string (ISO 8601 Date)",
    responsable: "string",
    equipo_afectado: "string",
    direccion_mac: "string (MAC address format)",
    dependencia: "string",
    estado_equipo: "'Infectado' | 'Mitigado' | 'En Alerta'",
    acciones_tomadas: "string",
    hash: "string",
    nivel_amenaza: "'No Detectado' | 'Bajo' | 'Medio' | 'Alto' | 'Crítico' | 'Desconocido'",
    detalles: "string",
    estado: "'Abierto' | 'Pendiente' | 'Cerrado'",
};
