// This file defines the structure of the data models for documentation purposes.
// It is used to generate a JSON representation of the system's data structure.

const incidentWorkstreamTrackerStructure = {
  id: "string (autogenerated)",
  date: "string (YYYY-MM-DD)",
  priority: "'Alta' | 'Media' | 'Baja'",
  status: "'New' | 'In Progress' | 'Complete' | 'In Review' | 'Backlog'",
  workstream: "string",
  task: "string",
  assignedTo: "string",
  dateUpdate: "string (YYYY-MM-DD)",
  dateComplete: "string (YYYY-MM-DD)",
};

const incidentSystemStructure = {
  id: "string (autogenerated)",
  status: "string",
  earliestEvidence: "string (ISO 8601 Date)",
  latestEvidence: "string (ISO 8601 Date)",
  hostname: "string",
  ipAddress: "string",
  domain: "string",
  systemRole: "string",
  systemOperating: "string",
  details: "string",
  notes: "string",
};

const incidentHostIndicatorStructure = {
  id: "string (autogenerated)",
  fullPath: "string",
  sha256: "string",
  sha1: "string",
  md5: "string",
  earliestEvidence: "string (ISO 8601 Date)",
  latestEvidence: "string (ISO 8601 Date)",
  attackAlignment: "string",
  notes: "string",
};

const incidentNetworkIndicatorStructure = {
  id: "string (autogenerated)",
  assignment: "string",
  status: "'Sospechoso' | 'Confirmado' | 'Under Investigation' | 'Unrelated'",
  indicator: "string",
  detail: "string",
  latestEvidence: "string (ISO 8601 Date)",
  source: "string",
  notes: "string",
};

const incidentEvidenceTrackerStructure = {
  id: "string (autogenerated)",
  evidenceType: "string",
  evidenceSource: "string",
  date: "string (ISO 8601 Date)",
  dateReceived: "string (ISO 8601 Date)",
  evidenceLocation: "string",
  notes: "string",
};

const incidentApplicationStructure = {
  id: "string (autogenerated)",
  submittedBy: "string",
  status: "'compromised-malware' | 'tools' | 'config-changes' | 'accessed-confirmed' | 'unauthorized-access' | 'potentially-accessed' | 'suspected-unauthorized-access'",
};

const incidentForensicStructure = {
  id: "string (autogenerated)",
  highFidelityForensicKeywords: "string",
  note: "string",
};

export const incidentStructure = {
  id: "string (autogenerated, e.g., 'INC-001')",
  title: "string",
  description: "string",
  status: "'Identificación' | 'Contención' | 'Mitigación' | 'Recuperación' | 'Post-incidente' | 'Cerrado'",
  severity: "'Low' | 'Medium' | 'High' | 'Critical'",
  reportedAt: "string (ISO 8601 Date)",
  reporter: {
    name: "string",
    email: "string (email format)",
  },
  assignedTo: {
    name: "string",
    email: "string (email format)",
  },
  updates: "Array of { timestamp: string (ISO 8601 Date), update: string }",
  workstreamAssignment: {
    scoping: "string (assignee name)",
    triage: "string (assignee name)",
    intelligence: "string (assignee name)",
    impact: "string (assignee name)",
  },
  workstreamTracker: `Array of objects with structure: ${JSON.stringify(incidentWorkstreamTrackerStructure)}`,
  systems: `Array of objects with structure: ${JSON.stringify(incidentSystemStructure)}`,
  hostIndicators: `Array of objects with structure: ${JSON.stringify(incidentHostIndicatorStructure)}`,
  networkIndicators: `Array of objects with structure: ${JSON.stringify(incidentNetworkIndicatorStructure)}`,
  intelligence: {
    status: "'Red' | 'Yellow' | 'Green'",
    rfi: "'Unanswered' | 'Awaiting Response' | 'Answered'",
    response: "string",
    sourceFile: "string (filename)",
  },
  evidenceTracker: `Array of objects with structure: ${JSON.stringify(incidentEvidenceTrackerStructure)}`,
  applications: `Array of objects with structure: ${JSON.stringify(incidentApplicationStructure)}`,
 forensics: `Array of objects with structure: ${JSON.stringify(incidentForensicStructure)}`,
  authorization: {
    authorizerName: "string",
    authorizerRank: "string",
    catalog: "string",
  },
};

export const detectionStructure = {
    id: "string (autogenerated, e.g., 'DET-001')",
    tipo_incidente: "string",
    prioridad: "'Baja' | 'Media' | 'Alta' | 'Crítica'",
    fecha_incidente: "string (ISO 8601 Date)",
    responsable: "string",
    equipo_afectado: "string",
    direccion_mac: "string (MAC address format)",
    dependencia: "string",
    estado_equipo: "'Infectado' | 'Mitigado' | 'En Alerta'",
    acciones_tomadas: "string",
    hash: "string",
    nivel_amenaza: "'No Detectado' | 'Bajo' | 'Medio' | 'Alto' | 'Crítico' | 'Desconocido'",
    detalles: "string",
    estado: "'Abierto' | 'Pendiente' | 'Cerrado'",
};
